name: Sync upstream
# This runs every day on 1000 UTC
on:
  schedule:
    - cron: '0 10 * * *'
  # Allows manual workflow run
  workflow_dispatch:

# Don't seem to be able to restrict this down since
# it needs to be able to push workflows, but that
# permission is not available here.
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync with upstream
        uses: DataDog/sync-upstream-release-tag@main
        with:
          github_actor: "${GITHUB_ACTOR}"
          github_repository: "${GITHUB_REPOSITORY}"
          github_token: ${{ secrets.WORKFLOW_TOKEN }}
          date_suffix: "%Y%V"
          upstream_repo: kubernetes/cloud-provider-aws